version: "3.8"

services:
  mongodb:
    image: mongo:latest
    ports:
      - "${MONGODB_PORT}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    volumes:
      - mongodb:/data/db
    command: mongod
    restart: always
    networks:
      - database

  faker:
    build:
      dockerfile: Dockerfile
      context: .
      args:
        DIR: main
    env_file:
      - .env
    depends_on:
      - mongodb
    restart: always
    ports:
      - "3000:3000"
    networks:
      - database

volumes:
  mongodb: { }
networks:
  database:
